### ISSUE TITLE
cyrillic symbols render as black squares

### ISSUE THREAD

**Issue by Lorloz** [nigma/django-easy-pdf#12]
hello!

trying to use this awesome app.

it works fine with English words in template, but when rendering a template into PDF with Russian symbols they are rendered as black squares

any thoughts on this?

my template:

{% extends "easy_pdf/base.html" %}

{% block extra_style %}
{% endblock %}

{% block content %}

```
<section id="manager" class="margint40">

    <div class="container">

        <div class="row margint10">
            <div class="content col-lg-12 clearfix">
                <h1>Заказ #{{ order.pk }} от {{ order.created }}</h1>
                ololol
            </div>
        </div>

    </div>

</section>
```

{% endblock %}

and below is the rendered PDF

![client](https://cloud.githubusercontent.com/assets/7036164/4866855/d4d3b63e-612f-11e4-9fea-9ae09f48ced8.jpg)

**Comment by litwisha** [comment]
Cyrilic font is not working

**Comment by kav2k** [comment]
Since this is number 1 place in Google for this question, here's a solution.

This is [the code that supplies the font files](https://github.com/nigma/django-easy-pdf/blob/360f75cf5258558370538a4ba20c4dbe7c91e418/easy_pdf/rendering.py#L23-L46):

    if settings.STATIC_URL and uri.startswith(settings.STATIC_URL):
        path = os.path.join(settings.STATIC_ROOT, uri.replace(settings.STATIC_URL, ""))
    elif settings.MEDIA_URL and uri.startswith(settings.MEDIA_URL):
        path = os.path.join(settings.MEDIA_ROOT, uri.replace(settings.MEDIA_URL, ""))
    else:
        path = os.path.join(settings.STATIC_ROOT, uri)

So, your font must be either in STATIC_ROOT or MEDIA_ROOT on the server's filesystem. Which means:

1) Add the font to static files of your project (assuming your static files are set up properly).
2) **Important:** run `python manage.py collectstatic`, so the file is actually copied there, _even if you run the development server_.
3) If you:
  * placed your font into `static/fonts/awesomefont.ttf` of your project
  * your `STATIC_URL` is, say `/static_files/`

Then you can use either of those:

    /* Relative to static files' root */
    @font-face { font-family: Whipsmart; src: url(fonts/pdf.ttf); }
    /* Full static URL */
    @font-face { font-family: Whipsmart; src: url(/static_files/fonts/pdf.ttf); }

Again, please note - the font will be loaded by `xhtml2pdf` utility, not the browser, so those files must be local to the machine Django is running on.

**Comment by Geebz** [comment]
@kav2k When I trying to add custom fonts, I always have the same error: 

>TypeError: 'NotImplementedType' object is not iterable

I`ve seen where the error appear and here is what I got 

![2016-08-30 19 40 12](https://cloud.githubusercontent.com/assets/11044968/18098235/0a31e0a2-6eea-11e6-9479-284eb84ae9cc.png)

Looks like I have a problem with url, but I have no idea how to solve this issue. I\`ve tried change src: url() different ways, but it is not working. 
Here\`s my code 


```python
{% extends "easy_pdf/base.html" %}
{% load staticfiles %}

{% block extra_style %}
    <style type="text/css">
    @font-face {
        font-family: Palatino Linotype; src: url({% static 'automobiles/fonts/bold.ttf' %});
    }
    body{
        font-family: "Palatino Linotype", Arial, sans-serif;
        color: #333333;
    }
    </style>
{% endblock extra_style %}

{% block content %}
    <div class="container">
        <h1>PYTHON3 RULES</h1>
        <p>Это должно работать</p>
        <h3>Но библиотеке что-то не нравится</h3>
    </div>
{% endblock content %}
```

**Comment by freeworlder** [comment]
@Geebz 
For those getting not implemented error, use my fork of xhtml2pdf that is a little corrected for python3. The error is python 3 specific (filter returns object, not a list, see commit). 
Django-easy-pdf depends on xhtml2pdf.
Fork: https://github.com/freeworlder/xhtml2pdf
